# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 367979644984529e87cfb8880d28f05486d9fc0504dcbd32e1f9569eaa9b730d3b9d0bc3ac4b3bcef7dcd8e23faed3cac819034fe681ce1159fc77f90b527cec

test:
  secret_key_base: 20f59d48074477296909abcaca46d6df20a257a728332370e95171265c4f163409dd491ad6fcb48054d29d1178116473141d6b4ad4503a2801f23d683b7da076

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
